### ISSUE TITLE
Don't support null safety

### ISSUE THREAD

**Issue by bugrevealingbme** [anuoua/system_properties#1]
Cannot run with sound null safety, because the following dependencies
don't support null safety:  - package:system_properties

**Comment by SalihCanBinboga** [comment]
#2 I've created a pull request about null safety. You can just wait for approval pull request by @anuoua

**Comment by bugrevealingbme** [comment]
> #2 I've created a pull request about null safety. You can just wait for approval pull request by @anuoua

Thank you.

**Comment by anuoua** [comment]
done #2 ，thanks for contribution.

**Comment by anuoua** [comment]
@bugrevealingbme I have no environment to test
